name = "bingwlapi-scheduler"
main = "worker/index.js" 

[vars]
GITHUB_USERNAME = "YOUR_GITHUB_USERNAME"
GITHUB_REPONAME = "bingwlapi"

# Secret for GitHub API token
# 使用 wrangler secret put GITHUB_TOKEN 来设置
# [[secrets]]
# GITHUB_TOKEN

# 使用数组格式定义所有 cron 触发器
[triggers]
crons = ["35 18 * * *", "1 0,5,15,16,23 * * *"]

# 开启日志推送
[log]
logpush = true
