name = "bingwlapi"
main = "src/worker.js"
compatibility_date = "2025-12-01"

[assets]
directory = "dist"

[build]
command = "npm run build"

[vars]
# GITHUB_TOKEN = "YOUR_GITHUB_TOKEN"
# GITHUB_USERNAME = "YOUR_GITHUB_USERNAME"
GITHUB_REPONAME = "bingwlapi"

[triggers]
crons = ["35 18 * * *", "1 0,5,15,16,23 * * *"]

[log]
logpush = true

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
