name: Update de-DE-fr-FR-it-IT Data

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Fetch new data for de-DE
        run: npm run get:de-DE

      - name: Commit de-DE data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/de-DE.json
          COMMIT_MSG="Update de-DE data $(date -u +'%Y-%m-%d %H:%M:%S') UTC / $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S') GMT+8"
          git diff --staged --quiet || git commit -m "$COMMIT_MSG"

      - name: Fetch new data for fr-FR
        run: npm run get:fr-FR

      - name: Commit fr-FR data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/fr-FR.json
          COMMIT_MSG="Update fr-FR data $(date -u +'%Y-%m-%d %H:%M:%S') UTC / $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S') GMT+8"
          git diff --staged --quiet || git commit -m "$COMMIT_MSG"

      - name: Fetch new data for it-IT
        run: npm run get:it-IT

      - name: Commit it-IT data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/it-IT.json
          COMMIT_MSG="Update it-IT data $(date -u +'%Y-%m-%d %H:%M:%S') UTC / $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S') GMT+8"
          git diff --staged --quiet || git commit -m "$COMMIT_MSG"

      - name: Push changes
        run: git push
